[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://festival-be.onrender.com/:splat"
  status = 200
  force = true
  headers = {
    X-From = "Netlify",
    Access-Control-Allow-Origin = "*",
  }